backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: true
    negative_slope: 0.2
  name: Conv64F
classifier:
  kwargs:
    n_k: 3
  name: ADM
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/ADM.yaml
- backbones/Conv64F.yaml
query_num: 15
shot_num: 1
test_episode: 100
train_episode: 100
way_num: 2
