backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
    maxpool_last2: true
  name: resnet12
classifier:
  kwargs:
    n_k: 3
  name: ADM
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/ADM.yaml
- backbones/Conv64F.yaml
n_gpu: 1
query_num: 15
shot_num: 10
test_episode: 2000
train_episode: 100
way_num: 2
