backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
classifier:
  kwargs:
    n_k: 3
  name: ADM
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/ADM.yaml
- backbones/Conv64F.yaml
n_gpu: 1
query_num: 15
shot_num: 10
test_episode: 100
train_episode: 100
way_num: 2
