Convclassifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      lr: 1e-2
      test_iter: 10
      train_iter: 5
  name: ANIL
backbone: &id001
  kwargs: null
  name: resnet18
backboneConv32F:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
backboneConv64F:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
backboneresnet12:
  kwargs:
    keep_prob: 0.0
  name: resnet12
backboneresnet18: *id001
classifier: &id002
  kwargs:
    feat_dim: 512
    inner_param:
      lr: 1e-3
      test_iter: 10
      train_iter: 5
  name: ANIL
data_root: data/consolidated_seeds_dataset
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
n_gpu: 1
optimizer:
  kwargs:
    lr: 1e-3
  name: Adam
  other: null
query_num: 15
resnet12classifier:
  kwargs:
    feat_dim: 640
    inner_param:
      lr: 1e-3
      test_iter: 10
      train_iter: 5
  name: ANIL
resnet18classifier: *id002
result_root: ./results
shot_num: 5
test_episode: 600
train_episode: 2000
way_num: 2
