backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
classifier:
  kwargs:
    atten_scale_value: 50
    feat_dim: 64
    from_value: 0.4
    scale_value: 30
    value_interval: 0.5
  name: ATLNet
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/ATL_NET.yaml
- backbones/Conv64F.yaml
n_gpu: 1
query_num: 15
shot_num: 5
test_episode: 100
train_episode: 100
way_num: 2
