backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
classifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          lr: 1e-3
        name: Adam
      inner_train_iter: 100
    num_class: 64
  name: Baseline
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Baseline.yaml
- backbones/Conv64F.yaml
n_gpu: 1
query_num: 15
shot_num: 1
test_episode: 2000
train_episode: 100
way_num: 2
