backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
batch_size: 128
classifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          lr: 1e-2
        name: Adam
      inner_train_iter: 100
    num_class: 351
  name: BaselinePlus
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Baseline++.yaml
- backbones/resnet18.yaml
n_gpu: 1
query_num: 15
shot_num: 5
test_episode: 100
train_episode: 100
way_num: 2
