backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
classifier:
  kwargs:
    HW: 10
    nFeat: 64
    num_class: 64
    scale_cls: 7
  name: CAN
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/CAN.yaml
- backbones/Conv64F.yaml
n_gpu: 1
query_num: 15
shot_num: 5
test_episode: 100
train_episode: 100
way_num: 2
