backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
classifier:
  kwargs:
    HW: 10
    nFeat: 64
    num_class: 64
    scale_cls: 7
  name: CAN
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/CAN.yaml
- backbones/Conv64F.yaml
n_gpu: 1
query_num: 15
shot_num: 10
test_episode: 2000
train_episode: 100
way_num: 2
