augment: true
augment_method: DeepBdcAugment
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
  name: resnet18
batch_size: 64
classifier:
  kwargs: null
  name: DeepBDC
device_ids: 0
episode_size: 1
epoch: 100
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
lr_scheduler:
  kwargs:
    gamma: 0.1
    milestones:
    - 40
    - 80
  name: MultiStepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.0001
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0005
  name: SGD
  other: null
pretrain_path: ./results/DeepBDC_Pretrain-miniImageNet--ravi-resnet12Bdc-5-1-Feb-08-2023-17-07-27/checkpoints/emb_func_best.pth
query_num: 15
save_part:
- emb_func
- cls_classifier
shot_num: 1
test_episode: 2000
test_epoch: 5
test_query: 15
test_shot: 1
test_way: 5
train_episode: 100
way_num: 2
