backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
classifier:
  kwargs:
    balance: 0.5
    hdim: 1600
    mode: euclidean
    temperature: 1.0
    temperature2: 1.0
  name: FEAT
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/FEAT.yaml
- backbones/WRN.yaml
n_gpu: 1
query_num: 15
shot_num: 5
test_episode: 100
train_episode: 100
way_num: 2
