backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
classifier:
  kwargs:
    encoder_penalty_weight: 1e-9
    feat_dim: 640
    hid_dim: 64
    inner_para:
      finetune_iter: 5
      finetune_lr: 1e-2
      iter: 5
      lr: 1e-2
    kl_weight: 1e-3
    orthogonality_penalty_weight: 1e-3
  name: LEO
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/LEO.yaml
- backbones/resnet12.yaml
n_gpu: 1
pretrain_path: ./results/checkpoint.pth
query_num: 15
shot_num: 1
test_episode: 2000
test_query: 15
test_shot: 1
test_way: 5
train_episode: 100
way_num: 2
