Convclassifier:
  kwargs:
    encoder_penalty_weight: 1e-9
    feat_dim: 1600
    hid_dim: 160
    inner_para:
      finetune_iter: 5
      finetune_lr: 1e-2
      iter: 5
      lr: 1e-2
    kl_weight: 1e-3
    orthogonality_penalty_weight: 1e-3
  name: LEO
backbone: 
  kwargs: null
  name: resnet18
backboneConv32F:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
backboneConv64F:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
backboneresnet12:
  kwargs:
    keep_prob: 0.0
  name: resnet12
backboneresnet18: *id001
classifier: &id002
  kwargs:
    encoder_penalty_weight: 1e-9
    feat_dim: 512
    hid_dim: 50
    inner_para:
      finetune_iter: 5
      finetune_lr: 1e-2
      iter: 5
      lr: 1e-2
    kl_weight: 1e-3
    orthogonality_penalty_weight: 1e-3
  name: LEO
data_root: data/consolidated_seeds_dataset
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/LEO.yaml
- backbones/resnet12.yaml
n_gpu: 1
pretrain_path: ./results/checkpoint.pth
query_num: 15
resnet12classifier:
  kwargs:
    encoder_penalty_weight: 1e-9
    feat_dim: 640
    hid_dim: 64
    inner_para:
      finetune_iter: 5
      finetune_lr: 1e-2
      iter: 5
      lr: 1e-2
    kl_weight: 1e-3
    orthogonality_penalty_weight: 1e-3
  name: LEO
resnet18classifier: *id002
result_root: ./results
shot_num: 1
test_episode: 600
test_query: 15
test_shot: 1
test_way: 5
train_episode: 2000
way_num: 2
