backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
    use_running_statistics: true
  name: Conv64F
classifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      lr: 1e-2
      test_iter: 10
      train_iter: 5
  name: MAML
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
n_gpu: 1
optimizer:
  kwargs:
    lr: 1e-3
  name: Adam
  other: null
query_num: 15
shot_num: 1
test_episode: 100
train_episode: 100
way_num: 2
