Convclassifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      iter: 10
    num_classes: 64
    use_MTL: true
  name: MTL
backbone: &id001
  kwargs:
    keep_prob: 0.0
  name: resnet12
backboneConv32F:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
backboneConv64F:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
backboneresnet12: *id001
backboneresnet18:
  kwargs: null
  name: resnet18
classifier: &id002
  kwargs:
    feat_dim: 640
    inner_param:
      iter: 10
    num_classes: 64
    use_MTL: true
  name: MTL
data_root: data/consolidated_seeds_dataset
device_ids: 0
episode_size: 1
epoch: 100
include:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- backbones/Conv64F.yaml
- classifiers/MTL_meta.yaml
n_gpu: 1
pretrain_path: ./results/checkpoint.pth
query_num: 15
resnet12classifier: *id002
resnet18classifier:
  kwargs:
    feat_dim: 512
    inner_param:
      iter: 10
    num_classes: 64
    use_MTL: true
  name: MTL
result_root: ./results
shot_num: 1
test_episode: 2000
train_episode: 100
way_num: 2
