backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
classifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      iter: 10
    num_classes: 64
    use_MTL: true
  name: MTL
device_ids: 0
episode_size: 1
epoch: 100
include:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- backbones/Conv64F.yaml
- classifiers/MTL_meta.yaml
n_gpu: 1
pretrain_path: ./results/checkpoint.pth
query_num: 15
shot_num: 1
test_episode: 2000
train_episode: 100
way_num: 2
