backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
    use_running_statistics: true
  name: Conv64F
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Proto.yaml
- backbones/resnet12.yaml
n_gpu: 1
query_num: 15
shot_num: 1
test_episode: 100
train_episode: 100
way_num: 2
