backbone:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: true
    negative_slope: 0.2
  name: Conv64F
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/R2D2.yaml
query_num: 15
shot_num: 1
test_episode: 100
test_query: 15
test_shot: 1
test_way: 5
train_episode: 100
way_num: 2
