backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
    use_running_statistics: true
  name: Conv64F
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/R2D2.yaml
n_gpu: 1
query_num: 15
shot_num: 10
test_episode: 2000
test_query: 15
test_shot: 1
test_way: 5
train_episode: 100
way_num: 2
