backbone: 
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
backboneConv32F:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
backboneConv64F: *id001
backboneresnet12:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
  name: resnet12
backboneresnet18:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
  name: resnet18
classifier:
  kwargs:
    alpha: 0.5
    classifier_path: ./results/RFSModel-miniImageNet--ravi-resnet18-5-1-Sep-23-2021-15-24-44/checkpoints/classifier_best.pth
    emb_func_path: ./results/RFSModel-miniImageNet--ravi-resnet18-5-1-Sep-23-2021-15-24-44/checkpoints/emb_func_best.pth
    feat_dim: 512
    gamma: 0.5
    is_distill: false
    num_class: 64
  name: RFSModel
data_root: data/consolidated_seeds_dataset
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/RFS.yaml
- backbones/resnet18.yaml
n_gpu: 1
query_num: 15
result_root: ./results
save_part:
- emb_func
- classifier
shot_num: 10
test_episode: 600
train_episode: 2000
way_num: 2
