backbone: 
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
  name: Conv32F
backboneConv32F: *id001
backboneConv64F:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
  name: Conv64F
backboneresnet12:
  kwargs:
    keep_prob: 0.0
  name: resnet12
backboneresnet18:
  kwargs: null
  name: resnet18
batch_size: 128
classifier:
  kwargs:
    alpha: 0.1
    cls_classifier_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/cls_classifier_best.pth
    emb_func_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/emb_func_best.pth
    feat_dim: 1600
    gamma: 1.0
    is_distill: false
    num_class: 64
  name: SKDModel
data_root: data/consolidated_seeds_dataset
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/SKD.yaml
- backbones/resnet12.yaml
n_gpu: 1
query_num: 15
result_root: ./results
save_part:
- emb_func
- cls_classifier
shot_num: 5
test_episode: 600
train_episode: 2000
way_num: 2
