backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
    maxpool_last2: true
  name: resnet12
batch_size: 128
classifier:
  kwargs:
    alpha: 0.1
    cls_classifier_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/cls_classifier_best.pth
    emb_func_path: ./results/SKDModel-miniImageNet--ravi-Conv64F-5-1-Sep-23-2021-15-16-27/checkpoints/emb_func_best.pth
    feat_dim: 1600
    gamma: 1.0
    is_distill: false
    num_class: 64
  name: SKDModel
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/SKD.yaml
- backbones/resnet12.yaml
n_gpu: 1
query_num: 15
save_part:
- emb_func
- cls_classifier
shot_num: 1
test_episode: 2000
train_episode: 100
way_num: 2
