backbone: &id001
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
backboneConv32F:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
backboneConv64F: *id001
backboneresnet12:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
  name: resnet12
backboneresnet18:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
  name: resnet18
classifier:
  kwargs:
    feat_dim: 1600
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          lr: 1e-3
        name: Adam
      inner_train_iter: 100
    num_class: 64
  name: Baseline
data_root: data/consolidated_seeds_dataset
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Baseline.yaml
- backbones/Conv64F.yaml
n_gpu: 1
query_num: 15
result_root: ./results
shot_num: 1
test_episode: 600
train_episode: 2000
way_num: 2
