backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    negative_slope: 0.2
  name: Conv32F
classifier:
  kwargs:
    d_theta: 256
    drop_rate: 0.5
    feat_dim: 1600
    sample_num: 10
  name: VERSA
deterministic: false
device_ids: 0
episode_size: 1
epoch: 100
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
n_gpu: 1
query_num: 15
shot_num: 10
test_episode: 2000
test_query: 15
test_shot: 5
test_way: 5
train_episode: 100
way_num: 2
