backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
    maxpool_last2: true
  name: resnet12
classifier:
  kwargs:
    d_theta: 256
    drop_rate: 0.5
    feat_dim: 1600
    sample_num: 10
  name: VERSA
deterministic: false
device_ids: 0
episode_size: 1
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
n_gpu: 1
query_num: 15
shot_num: 5
test_episode: 100
test_query: 15
test_shot: 5
test_way: 5
train_episode: 100
way_num: 2
